### ISSUE TITLE
Doesn't work with "WindowsAzure.Storage" versions > "4.1.0"

### ISSUE THREAD

**Issue by ajoylabroo** [s-innovations/azure-table-storage-repository-pattern#1]
Hello,

First of all, great package. Thanks for writing it. I have tried to incorporate it in my ASP.NET 5 solution, but it doesn't work if I reference WindowsAzure.Storage Versions greater than 4.1.0. It works perfectly with 4.1.0. 

As you might know WindowsAzure.Storage is currently in 5.0.1-preview version and if you update your references, it would be great.

I installed it using Nuget (if that helps) just a few days back.

**Comment by pksorensen** [comment]
Cool seeing that you use it, without it having any kind of documentation :) 

I use it myself in a few projects that reference 5.0.0, without any problems. Where are you getting the package, from nuget or myget? Maybe I need to push an updated version to nuget also since my own development runs against my myget feed.

Assembly rebinding in web.config/app.config might also solve your problem. But if you let me know if you are compiling or getting from nuget, then I will try to update accordingly, since the latest source code already reference 5.0.0

**Comment by pksorensen** [comment]
I have pushed a new 2.0.0-alpha to nuget.  Its all the changes I been doing since the last release, but I havent used the time to track these changes so take a look if all the features you are using is still there. I recall that I did a small namespace change so if you build breaks, take a look for that.

**Comment by ajoylabroo** [comment]
Thanks for fixing. I was using nuget feed and after pulling in the latest version, I am able to use "WindowsAzure.Storage": "5.0.0" again.

You have done an amazing job of writing beautiful code repository along with Unit Tests which were more than sufficient in getting me started in terms of usage.

Thank you.
